version: "3.3"
services:
    server:
        build: ./ServerProject-DONT-IMPORT-INTO-UNITY
        restart: unless-stopped
        depends_on:
            - load_balancer

    load_balancer:
        container_name: ${COMPOSE_PROJECT_NAME}_load_balancer
        build: ./LoadBalancerProject-DONT-IMPORT-INTO-UNITY
        restart: unless-stopped
        ports:
            - "8080:8080"
        networks:
            app_net:
                ipv4_address: 10.5.0.2
ipam:
    driver: default
    config:
        - subnet: 10.5.0.0/16